// consts/filters.tsx

interface BrandFilter {
  label: string;
  models: string[];
}

export const BRAND: BrandFilter[] = [
  {
    label: "Toyota",
    models: [
      "Yaris",
      "Corolla",
      "Camry",
      "RAV4",
      "Hilux",
      "Land Cruiser",
      "Prado",
      "Hiace",
      "Avanza",
      "Fortuner",
      "C-HR",
      "Prius",
    ],
  },
  {
    label: "Renault",
    models: [
      "Clio",
      "Symbol",
      "Logan",
      "Sandero",
      "Duster",
      "Captur",
      "Kadjar",
      "Megane",
      "Talisman",
      "Koleos",
      "Scenic",
      "Kangoo",
    ],
  },
  {
    label: "Mercedes-Benz",
    models: [
      "Classe A",
      "Classe B",
      "Classe C",
      "Classe E",
      "Classe S",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "Classe V",
      "Sprinter",
    ],
  },
  {
    label: "Volkswagen",
    models: [
      "Golf",
      "Polo",
      "Passat",
      "Tiguan",
      "T-Roc",
      "Touareg",
      "Amarok",
      "Caddy",
      "Transporter",
      "Arteon",
      "Jetta",
      "Scirocco",
    ],
  },
  {
    label: "Hyundai",
    models: [
      "i10",
      "i20",
      "i30",
      "Elantra",
      "Accent",
      "Sonata",
      "Tucson",
      "Santa Fe",
      "Creta",
      "Kona",
      "Genesis",
      "H1",
    ],
  },
  {
    label: "Kia",
    models: [
      "Picanto",
      "Rio",
      "Cerato",
      "Optima",
      "Sportage",
      "Sorento",
      "Seltos",
      "Stonic",
      "Carnival",
      "Ceed",
      "Niro",
      "Soul",
    ],
  },
  {
    label: "Peugeot",
    models: [
      "208",
      "308",
      "508",
      "2008",
      "3008",
      "5008",
      "Partner",
      "Expert",
      "Boxer",
      "RCZ",
      "5008",
      "Rifter",
    ],
  },
  {
    label: "Dacia",
    models: [
      "Sandero",
      "Logan",
      "Duster",
      "Lodgy",
      "Dokker",
      "Spring",
      "Jogger",
      "Sandero Stepway",
    ],
  },
  {
    label: "BMW",
    models: [
      "Série 1",
      "Série 3",
      "Série 5",
      "Série 7",
      "X1",
      "X3",
      "X5",
      "X6",
      "X7",
      "Z4",
      "i3",
      "i8",
    ],
  },
  {
    label: "Audi",
    models: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "TT",
      "R8",
    ],
  },
  {
    label: "Ford",
    models: [
      "Fiesta",
      "Focus",
      "Fusion",
      "Mondeo",
      "EcoSport",
      "Kuga",
      "Edge",
      "Explorer",
      "Ranger",
      "F-150",
      "Mustang",
      "Transit",
    ],
  },
  {
    label: "Nissan",
    models: [
      "Micra",
      "Sunny",
      "Altima",
      "Maxima",
      "Qashqai",
      "X-Trail",
      "Juke",
      "Patrol",
      "Navara",
      "Leaf",
      "Note",
      "Sentra",
    ],
  },
  {
    label: "Citroën",
    models: [
      "C1",
      "C3",
      "C4",
      "C5",
      "Berlingo",
      "Jumpy",
      "C-Elysée",
      "C3 Aircross",
      "C5 Aircross",
      "DS3",
      "DS4",
      "DS7",
    ],
  },
  {
    label: "Chevrolet",
    models: [
      "Spark",
      "Aveo",
      "Cruze",
      "Malibu",
      "Captiva",
      "Trax",
      "Trailblazer",
      "Colorado",
      "Camaro",
      "Corvette",
      "Tahoe",
    ],
  },
  {
    label: "Opel",
    models: [
      "Corsa",
      "Astra",
      "Insignia",
      "Mokka",
      "Crossland",
      "Grandland",
      "Combo",
      "Vivaro",
      "Zafira",
      "Adam",
      "Karl",
    ],
  },
  {
    label: "Mitsubishi",
    models: [
      "Mirage",
      "Lancer",
      "Outlander",
      "ASX",
      "Eclipse Cross",
      "Pajero",
      "Pajero Sport",
      "L200",
      "i-MiEV",
    ],
  },
  {
    label: "Suzuki",
    models: [
      "Alto",
      "Swift",
      "Baleno",
      "Celerio",
      "Vitara",
      "S-Cross",
      "Jimny",
      "Ignis",
      "Ertiga",
      "Carry",
      "APV",
    ],
  },
  {
    label: "Seat",
    models: [
      "Ibiza",
      "Leon",
      "Toledo",
      "Ateca",
      "Arona",
      "Tarraco",
      "Alhambra",
      "Mii",
      "Cupra",
      "Cupra Formentor",
    ],
  },
  {
    label: "Skoda",
    models: [
      "Fabia",
      "Octavia",
      "Superb",
      "Rapid",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Scala",
      "Enyaq",
      "Citigo",
      "Roomster",
    ],
  },
  {
    label: "Fiat",
    models: [
      "500",
      "Panda",
      "Punto",
      "Tipo",
      "Doblo",
      "Ducato",
      "Fiorino",
      "Qubo",
      "500L",
      "500X",
      "Freemont",
      "Bravo",
    ],
  },
  {
    label: "Honda",
    models: [
      "Jazz",
      "Civic",
      "Accord",
      "CR-V",
      "HR-V",
      "Pilot",
      "City",
      "BR-V",
      "Fit",
      "Odyssey",
      "Stepwgn",
    ],
  },
  {
    label: "Mazda",
    models: [
      "2",
      "3",
      "6",
      "CX-3",
      "CX-5",
      "CX-9",
      "CX-30",
      "MX-5",
      "BT-50",
      "Demio",
      "Premacy",
    ],
  },
  {
    label: "Jeep",
    models: [
      "Renegade",
      "Compass",
      "Cherokee",
      "Grand Cherokee",
      "Wrangler",
      "Gladiator",
      "Patriot",
      "Commander",
      "Avenger",
    ],
  },
  {
    label: "Land Rover",
    models: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Range Rover",
      "Range Rover Sport",
      "Range Rover Evoque",
      "Range Rover Velar",
    ],
  },
  {
    label: "Volvo",
    models: [
      "S60",
      "S90",
      "V60",
      "V90",
      "XC40",
      "XC60",
      "XC90",
      "C40",
      "V40",
      "XC70",
      "S40",
    ],
  },
  {
    label: "Mini",
    models: [
      "Cooper",
      "Cooper S",
      "Clubman",
      "Countryman",
      "Convertible",
      "Paceman",
      "Coupe",
      "Roadster",
    ],
  },
  {
    label: "Lexus",
    models: ["IS", "ES", "GS", "LS", "UX", "NX", "RX", "LX", "RC", "LC"],
  },
  {
    label: "Infiniti",
    models: ["Q30", "Q50", "Q60", "QX30", "QX50", "QX60", "QX70", "QX80"],
  },
  {
    label: "Porsche",
    models: [
      "911",
      "Panamera",
      "Cayenne",
      "Macan",
      "Boxster",
      "Cayman",
      "Taycan",
      "Carrera",
    ],
  },
  {
    label: "Jaguar",
    models: [
      "XE",
      "XF",
      "XJ",
      "F-Pace",
      "E-Pace",
      "I-Pace",
      "F-Type",
      "X-Type",
    ],
  },
  {
    label: "SsangYong",
    models: [
      "Tivoli",
      "Korando",
      "Rexton",
      "Musso",
      "Actyon",
      "Kyron",
      "Rodius",
      "XLV",
    ],
  },
];

export const fuel_type: string[] = [
  "Gasoline",
  "Diesel",
  "Hybrid",
  "Electric",
  "LPG",
  "CNG",
];

export const transmission: string[] = [
  "Manual",
  "Automatic",
  "Semi-Automatic",
  "CVT",
];

export const seats: string[] = ["2", "4", "5", "6", "7", "8+"];

export const doors: string[] = ["2", "3", "4", "5"];

export const category: string[] = [
  "Sedan",
  "SUV",
  "Hatchback",
  "Coupe",
  "Convertible",
  "Minivan",
  "Pickup Truck",
  "Sports Car",
  "Luxury",
  "Compact",
  "Family",
  "Commercial",
];

export const yearRange: string[] = [
  "2020-2024",
  "2015-2019",
  "2010-2014",
  "2005-2009",
  "2000-2004",
  "Before 2000",
];

export const priceRange: string[] = [
  "Under 1000 DZD",
  "1000 - 2000 DZD",
  "2000 - 3000 DZD",
  "3000 - 5000 DZD",
  "5000 - 7000 DZD",
  "7000+ DZD",
];

export const features: string[] = [
  "Air Conditioning",
  "Bluetooth",
  "Navigation System",
  "Backup Camera",
  "Parking Sensors",
  "Sunroof/Moonroof",
  "Leather Seats",
  "Heated Seats",
  "Apple CarPlay/Android Auto",
  "Keyless Entry",
  "Push Button Start",
  "Cruise Control",
  "Alloy Wheels",
  "Roof Rack",
  "Towing Package",
  "4WD/AWD",
  "Child Seat",
  "Pet Friendly",
];
